### ISSUE TITLE
to_binary, from_binary functions

### ISSUE THREAD

**Issue by Licenser** [HdrHistogram/hdr_histogram_erl#1]
It would be wonderful if the memory for the histogram could be dumped to memory and following that restored from memory.

**Comment by darach** [comment]
Hi Heinz. I can see how that might be useful. :+1:

**Comment by darach** [comment]
Added in 606563a7eb42aa29fbf6aec0f0146eb2a1adfc60. This uses encode/decode
via hdr_histogram_log which is relatively standard across the Java and C variants with
compression.

**Comment by darach** [comment]
Done.
