### ISSUE TITLE
Record_many '0' values fails with 'value_out_of_range'

### ISSUE THREAD

**Issue by dcorbacho** [HdrHistogram/hdr_histogram_erl#13]
Record many zeros fails, while record a single zero succeeds. Is this a bug, a feature or something I don't understand about the meaning of record_many?

```
8> {ok, H} = hdr_histogram:open(600, 5).
{ok,<<>>}
9> hdr_histogram:record(H, 0).
ok
10> hdr_histogram:record_many(H, 0, 1).
{error,value_out_of_range}
```

**Comment by darach** [comment]
This is a bug I introduced when I fixed issue 004 but the tests didn't cover the full value space of legal values for the record_many case and the regression test added only covered the basic record. 

Fix with regression test pushed, just waiting on Travis CI to bless then i'll merge and tag a patch release for you.

Thanks for reporting the issue!

**Comment by darach** [comment]
I should note that the lowest trackable value is in fact 1 here, but zero should be acceptable as a value.

**Comment by darach** [comment]
Fixed in #14 and tagged 0.2.6. Please confirm fix and close if you are satisfied it resolves your issue.

**Comment by dcorbacho** [comment]
That's good. Thanks!

**Comment by darach** [comment]
You are most welcome! :)
