### ISSUE TITLE
hdr_histogram counter-example

### ISSUE THREAD

**Issue by jlouis** [HdrHistogram/hdr_histogram_erl#21]
Here is a counterexample which fails based on the new EQC tests:

```
Shrinking xxxxxxxxxxxxxxxxxx.x..xxxx..x.xx.....xxx...........x...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(25 times)
{{call,hdr_bin_tests_eqc,open,[524287,5]},{c,[{compression,zlib}]},{0,0,0}}
#{max => 0,
  mean => 0.0,
  median => 0.0,
  mem_size => 4194376,
  min => 0,
  p99 => 0.0,
  p99999 => 0.0,
  stddev => 0.0,
  total_count => 0} /= {exception,error,badarg}
[prop_to_bin]
```

Note that we have opened the `hdr_histogram` with 5 significant digits, and this fails once we try to push the histogram to a binary and re-read it. We simply get a badarg error on the read. Here is the command we fired:

```
{call,hdr_bin_tests_eqc,open,[524287,5]}
```

**Comment by Licenser** [comment]
As mentioned in the PR, it s actually a with `to_binary` here claiming that the file binary passed in is not a HDR binary:

``` erlang
4> {ok, H} = hdr_histogram:open(524287,5).
{ok,<<>>}
5> hdr_histogram:to_binary(H).
{error,bad_hr_binary}
```

**Comment by jlouis** [comment]
Yes. It looks like it works with 1..4 but not with 5 for some reason. I'm not sure what is happening here. And it is a good catch @Licenser. I just naively thought it was on the other path.

**Comment by Licenser** [comment]
Yea me too ;) then I wanted to print out the 'bad' binary and noticed it isn't a binary at all.

**Comment by Licenser** [comment]
I want to add here that the error is only affecting to_binary:

``` erlang
4> {ok, H} = hdr_histogram:open(524287,5).
{ok,<<>>}
5> hdr_histogram:to_binary(H).
{error,bad_hdr_binary}
6> hdr_histogram:record(H, 7).
ok
7> hdr_histogram:to_binary(H).
{error,bad_hdr_binary}
8> hdr_histogram:max(H).
7
```
