### ISSUE TITLE
Could you please make a new release?

### ISSUE THREAD

**Issue by pjhades** [HdrHistogram/hdr_histogram_erl#35]
Hello. The latest tag is still 0.3.2 which does not include later patches. It makes some of our projects fail to build. I used to have a PR for one build issue but I think that has been fixed on master. Could you please make a new release? Thanks.

**Comment by tsloughter** [comment]
I'm going to try to find someone who can get in touch with Darach. Maybe he'll be open to adding someone as an additional maintainer.

I'd like to publish to hex especially.

**Comment by tsloughter** [comment]
So I am a maintainer now but need to get @Licenser to add me on hex so I can publish :)

**Comment by Licenser** [comment]
done!

**Comment by tsloughter** [comment]
I've published 0.4.0 to hex.
