### ISSUE TITLE
hdr_histogram_erl failed to compile with OTP23

### ISSUE THREAD

**Issue by wilburpolarlight** [HdrHistogram/hdr_histogram_erl#40]
I installed OTP 23.0 and found hdr_histogram_erl failed to compile (as a dependency of my application) with error 
`ld: library not found for -lerl_interface` 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`.
 I have no background in C integration with Erlang but I guess this is due to the modification on `erl_interface` in OTP23.

I think you guys might have noticed this or it is already a work in progress, but I would like to post here anyway in case someone encountered similar problem.

Thanks.

**Comment by hexedpackets** [comment]
@tsloughter Could you push up a new release with this fix in it? I just ran into the same error on OTP 24, master compiled fine.

**Comment by tsloughter** [comment]
@hexedpackets sorry for the delay. I'll publish now.

**Comment by tsloughter** [comment]
Done.
